### ISSUE TITLE
error: the following arguments are required: filepath

### ISSUE THREAD

**Issue by ghost** [AnalogMan151/splitNSP#2]
Doesn't seem to work for some reason. "error: the following arguments are required: filepath" is the error I get when I try to run it. Running Python 3.7 on windows 10.

**Comment by AnalogMan151** [comment]
Working as intended. Please review the usage instructions in the readme or by using the `-h` or `--help` command. 

This particular error is telling you to provide a file path to the file you wish to split.

**Comment by ghost** [comment]
I am providing the file path. It is in C:/nsp/game.nsp and the command given is "c:/nsp/splitNSP.py c:/nsp/game.nsp" I removed all spaces and special characters and changed the directory to as close to root as possible. I also ran -h and --help but I get the same error, with or without a path to the nsp.

**Comment by arkdev9** [comment]
Okay, try this. Put both the python file and nap file in the same folder, then from the directory, run this: `python splitNSP.py "game.nsp"`

**Comment by ghost** [comment]
That worked, thank you.
