### ISSUE TITLE
set archive flag

### ISSUE THREAD

**Issue by blairfancy** [AnalogMan151/splitNSP#3]
Hi,
you can use fatattr app to set any fat flag on linux. Probably macos have also this command.

**Comment by J7mbo** [comment]
MacOS doesn't :/

**Comment by AnalogMan151** [comment]
That’s correct. You can use the homebrew app NXShell to set the archive bit though after moving the folder to the Switch.

**Comment by J7mbo** [comment]
Thanks @AnalogMan151. I ended up using goldleaf / goldtree usb instead so didn't have to split files.

**Comment by AnalogMan151** [comment]
Updated readme to mention NX-Shell
