### ISSUE TITLE
set archive flag on switch

### ISSUE THREAD

**Issue by bombaygin** [AnalogMan151/splitNSP#4]
download the homebrew called "NXShell" and start it.
first, enable dev options under settings.
navigate to your tinfoil/nsp folder. press X on the new splitted folder.
go to options, archive bit
voila, now it appears on tinfoil! :)

**Comment by wendyliga** [comment]
nice to know you can archive bit on homebrew

thanks man @bombaygin

**Comment by gergokekesi** [comment]
You should add this to the README if you could please.

**Comment by msdos** [comment]
If using hekate, you can in options use `fix archive bit`.

**Comment by AnalogMan151** [comment]
Updated readme to mention NX-Shell
