### ISSUE TITLE
Module Object has no Attribute 'disk_usage'

### ISSUE THREAD

**Issue by bdpna** [AnalogMan151/splitNSP#5]
Drag and drop NSP file wasn't working, dropped to CMD line in Windows 10 and got this error.  What am I doing wrong?

  File "F:\Nintendo Switch Games\splitNSP.py", line 143, in <module>
    main()
  File "F:\Nintendo Switch Games\splitNSP.py", line 140, in main
    splitCopy(filepath)
  File "F:\Nintendo Switch Games\splitNSP.py", line 79, in splitCopy
    info = shutil.disk_usage(os.path.dirname(os.path.abspath(filepath)))
AttributeError: 'module' object has no attribute 'disk_usage'

**Comment by antipickle** [comment]
I had the same error in the terminal, but drag and drop worked

**Comment by DefinePvP** [comment]
Try using Python3 instead of Python2.  That was the solution for me.
