### ISSUE TITLE
NSP not found.

### ISSUE THREAD

**Issue by GrrrthTD** [AnalogMan151/splitNSP#8]
I opened a terminal in the folder that my NSP and split NSP are located in.  Ran "sudo python3 splitNSP.py filename.nsp" replacing "filename.nsp" with the name of my of the file I need split.  Also tried it with the whole file path.  It came back saying it couldn't find the file.

I'm sure it's something that I'm doing wrong, but can't figure it out.

**Comment by AnalogMan151** [comment]
You don't need to sudo to run this script. Sudo-ing would change the current working directory. If both the script AND the file are in the same folder you can just `./splitNSP.py filename.nsp`
